### ISSUE TITLE
undefined is not an object (evaluating 't.type') error qwith satori > ultra html

### ISSUE THREAD

**Issue by pi0** [unjs/undocs#42]
```
 ERROR  [nuxt] [request error] [unhandled] [500] undefined is not an object (evaluating 't.type')                                                       8:15:58 PM
  at S (/Users/pooya/Code/unjs-docs/node_modules/ultrahtml/dist/selector.js:0:5723)  
  at <anonymous> (/Users/pooya/Code/unjs-docs/node_modules/ultrahtml/dist/selector.js:287:29)  
  at <anonymous> (/Users/pooya/Code/unjs-docs/node_modules/ultrahtml/dist/selector.js:205:13)  
  at <anonymous> (/Users/pooya/Code/unjs-docs/node_modules/ultrahtml/dist/selector.js:211:34)  
  at visit (/Users/pooya/Code/unjs-docs/node_modules/ultrahtml/dist/index.js:174:22)  
  at visit (/Users/pooya/Code/unjs-docs/node_modules/ultrahtml/dist/index.js:177:19)  
  at C (/Users/pooya/Code/unjs-docs/node_modules/ultrahtml/dist/selector.js:210:11)  
  at <anonymous> (/Users/pooya/Code/unjs-docs/node_modules/ultrahtml/dist/transformers/inline.js:272:17)  
  at html (/Users/pooya/Code/unjs-docs/node_modules/satori-html/dist/index.js:4:10)  
  at <anonymous> (/Users/pooya/Code/unjs-docs/playground/.docs/.nuxt/prerender/chunks/renderer.mjs:82:202)  
  at processTicksAndRejections (:12:39)
```

/cc @harlan-zw haven't investigate yet but this started to happen recently you can reproduce with `bun i` + `bun dev:build` locally

**Comment by harlan-zw** [comment]
Related https://github.com/nuxt-modules/og-image/issues/112
