### ISSUE TITLE
No package manager auto-detected

### ISSUE THREAD

**Issue by ahmedragab20** [unjs/undocs#71]
### package.json
```json
{
  "private": true,
  "name": "docs",
  "scripts": {
    "dev": "undocs dev",
    "build": "undocs build"
  },
  "devDependencies": {
    "undocs": "latest"
  }
}
```

### node version
v20.10.0

### Reproduction

1)
```bash
pnpx giget gh:unjs/undocs/template docs --install
```

you'll get:
>  ERROR  No package manager auto-detected.

2)
```bash
pnpm install
```

3)
```bash
pnpm dev
```

>  ERROR  Cannot start nuxt:  Cannot find module nuxt imported from file:///Users/usr/dir/Projects/dir/dir/.docs, file:///Users/usr/dir/Projects/dir/dir/, file:///Users/usr/dir/Projects/dir/dir/.docs/_index.js, file:///Users/usr/dir/Projects/dir/dir/node_modules

### Describe the bug

after following the Reproduction steps, run the dev, the local will stay pending.

<img width="1624" alt="image" src="https://github.com/unjs/undocs/assets/71534456/81ca96b8-9266-4cca-9606-a20d7ab008d5">

### Logs

```sh
at \_resolve (.../doc/node_modules/.pnpm/mlly@1.6.1/node_modules/mlly/dist/index.mjs:2107:19)
at resolveSync (.../doc/node_modules/.pnpm/mlly@1.6.1/node_modules/mlly/dist/index.mjs:2116:10)
at resolvePathSync (.../doc/node_modules/.pnpm/mlly@1.6.1/node_modules/mlly/dist/index.mjs:2126:24)
at resolvePath (.../doc/node_modules/.pnpm/mlly@1.6.1/node_modules/mlly/dist/index.mjs:2130:28)
at importModule (.../doc/node_modules/.pnpm/@nuxt+kit@3.10.3/node_modules/@nuxt/kit/dist/index.mjs:2249:30)
at Module.buildNuxt (.../doc/node_modules/.pnpm/@nuxt+kit@3.10.3/node_modules/@nuxt/kit/dist/index.mjs:2597:130)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 1)
at async NuxtDevServer.\_load (.../doc/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev2.mjs:279:5)
at async NuxtDevServer.load (.../doc/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev2.mjs:184:7)
```

**Comment by peterroe** [comment]
Try `bun install` and `bun dev` maybe could help you :)

**Comment by pi0** [comment]
Hi. This should have been fixed in latest giget/nypm releases.
